### PR TITLE
memoized getColumns function #55

### PR DESCRIPTION
**Pull request by shri1897**

### CODE REVIEW

**Comment by GuillaumeJasmin** [comment]
Thanks for this PR.
Code can't work because `columns` is undefined here:
```
getColumns = memoize((columns) => { ... }
```
As you no longer use

```
const { columns } = this.props;
```

you have to pass `columns` to `getColumns(columns)` from render method

**Comment by shri1897** [comment]
> Thanks for this PR.
> Code can't work because `columns` is undefined here:
> 
> ```
> getColumns = memoize((columns) => { ... }
> ```
> 
> As you no longer use
> 
> ```
> const { columns } = this.props;
> ```
> 
> you have to pass `columns` to `getColumns(columns)` from render method


I have addressed the comments. Please review

**Comment by GuillaumeJasmin** [comment]
Thanks for this PR !
It's available in `v2.1.3`

**Comment by shri1897** [comment]
Thanks a lot :)

**Pull request merged**
